### ISSUE TITLE
Is there a way to custome the className of the element li?

### ISSUE THREAD

**Issue by cbfrank** [react-component/pagination#107]
Hi
Thanks for this component, I'd like to know if there is an api to set the element **li** className just like what we do to element **ul** with className on `<Pagination>`

Thanks

**Comment by paranoidjk** [comment]
What's your use case? can you explain why you want to add extra className?

**Comment by cbfrank** [comment]
rc-pagination use custom css class such as rc-**, but our project following the bootstrap css class, so we would like to use "page-item" on li, the problem is, the project is big, and we have frontend designer that will work and customize the default bootstrap css, that is to say, once he updated the default boostrap css, the pagination style will be updated as long as the page-item class on li element.
we can use itemRender to custom a inside the li with the default bootstrap class "page-link", but we can't change the render of li, and if possible, we also need to customize the total count block.

Thanks

**Comment by paranoidjk** [comment]
You can use `props.prefixCls`

**Comment by cbfrank** [comment]
Thanks, I will have a try

**Comment by paranoidjk** [comment]
please notice that change prefixCls will cause rc-pagination default style lose function，if you want to preserve default style at the same time，you can do a little trick，set prefixCls like `rc-pagination myclass`. But it will cause HTML file bigger at the same time.

**Comment by cbfrank** [comment]
Seems the class is not right, when I use this component as bellow:
<Pagination onChange={(pageIndex: number, pageSize: number) => onChange(pageIndex - 1, pageSize)}
                               current={this.props.table.pageData ? (this.props.table.pageData.pageIndex + 1) : 0}
                               total={this.props.table.totalDataItemsCount} pageSize={this.props.table.pageData.pageSize}
                               itemRender={itemRender}
                               prefixCls="rc-pagination page-item"
                               showTitle={true} showTotal={(total, range) => ` total ${total} items`}
                               className="pagination pagination-sm"/>

the generated li element will have class "rc-pagination page-item-item rc-pagination page-item-item-*" (* is a number)

**Comment by paranoidjk** [comment]
@cbfrank Then I suggest you use `itemRender` to custom your element https://github.com/react-component/pagination/blob/master/examples/itemRender.js#L25

**Comment by gardezii** [comment]
hey man I'm having a problem. The item render is not working

**Comment by lauriskuznecovs** [comment]
> hey man I'm having a problem. The item render is not working

`itemRender` works a little different way that you could expect. It allows to render custom markup as a children of `<li>`, but if I need to customize title for <li>, then its not possible.
