### ISSUE TITLE
Can't render the css provided by you guys

### ISSUE THREAD

**Issue by Gardezi1** [react-component/pagination#126]
Hello guys, 

I'm trying to use your paginator but the problem is I'm not able to get the css as shown in your example. can you guys help me out maybe there is something I'm not doing right. HEre is my code 

```

import Pagination from 'rc-pagination'
import 'rc-pagination/assets/index.css'


<Pagination className="ant-pagination" defaultCurrent={3} total={450} />

```

**Comment by yesmeck** [comment]
Could you reproduce it on https://codesandbox.io/?

**Comment by Gardezi1** [comment]
well that's odd. It's working in codesandbox. It looks like my project is not picking up the css somehow. 

https://codesandbox.io/s/7kp1oojzp1

I need to debug and see what is it that is causing the problem
