### ISSUE TITLE
在onChange回调函数内使用this.setState后，点击页码后，页码没有变化（没有加载样式）

### ISSUE THREAD

**Issue by ldwstyle** [react-component/pagination#129]
<Pagination total={this.state.total} pageSize={5} onChange={(pageNum) => this.onPageNumChange(pageNum)}/>

onPageNumChange(pageNum){
        this.setState({
            total:100
        })
    }
回调函数内只要使用this.setState点击页面就无法加载样式，但是功能可以正常使用，是我的用法有问题吗？

**Comment by yutingzhao1991** [comment]
如果是 bug，可以通过 codesandbox.io 提供一个复现的链接看看。

**Comment by ldwstyle** [comment]
<Pagination total={this.state.total} pageSize={5} onChange={(pageNum) => this.onPageNumChange(pageNum)}/>
pageSize改成defaultPageSize就好了，感谢你的回复！
