### ISSUE TITLE
Is 'locale' working for all the languages? 

### ISSUE THREAD

**Issue by riteshchandna** [react-component/pagination#131]
Is there a way to change the language to English ('en_US')? I saw that there is an attribute 'locale' to change default language. However, it's not working for me. 

Could you please provide an example on how to use 'locale'.

**Comment by yutingzhao1991** [comment]
added a new demo for it, https://github.com/react-component/pagination/commit/5d1f37a0c5d22852ab652614b44f7be5a2c85c65.
