### ISSUE TITLE
Option to hide first and last pager

### ISSUE THREAD

**Issue by ladmerc2** [react-component/pagination#142]
It would be nice to have an option to hide/show the first and last pager buttons if they are not in view

**Comment by comradebeck** [comment]
I agree with @ladmerc2. Perhaps also separate settings for first and last. Last pager though should be conditional, i.e. if total prop exceeds a number. This will be beneficial for large result set in distributed systems when you want to eliminate to deep paging.

**Comment by zombieJ** [comment]
Wrap with `itemRender` can make it happen: http://react-component.github.io/pagination/examples/itemRender.html
