### ISSUE TITLE
Definition file is not included in the release

### ISSUE THREAD

**Issue by marcioluis** [react-component/pagination#164]
The definitions of the library is not found after installing it.

```
Could not find a declaration file for module 'rc-pagination'. '.../node_modules/rc-pagination/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/rc-pagination` if it exists or add a new declaration (.d.ts) file containing `declare module 'rc-pagination';`ts(7016).
```

The file rc-pagination.d.ts can't be found anywhere  inside de node_modules/rc-pagination folders.

Version: "rc-pagination": "1.17.8"

**Comment by ZhaoMuwei** [comment]
Typing file does exist, but seems to be missed in `files` field of package.json.
Made a PR here #168.
