### ISSUE TITLE
如何从外部修改  current ?

### ISSUE THREAD

**Issue by noyobo** [react-component/pagination#23]
componentWillReceiveProps 只修改了 current ，  然而 `<input type="text" value={this.state._current} ` [#195](https://github.com/react-component/pagination/blob/master/src/Pagination.jsx#L195) 是使用 `_current`

**Comment by noyobo** [comment]
https://github.com/react-component/pagination/blob/master/src/Pagination.jsx#L195

**Comment by ibigbug** [comment]
现在有什么需求无法满足?
