### ISSUE TITLE
The latest version of the style is a mess

### ISSUE THREAD

**Issue by king-lxt** [react-component/pagination#279]
The latest version of the style is a mess

**Comment by JulianSuringa** [comment]
mozilla browser 78.0.2 (64-bit)
![arrow left and right missing](https://user-images.githubusercontent.com/2208568/87632074-3aca8380-c76b-11ea-9b90-3cc85a805d59.png)

**Comment by xrkffgg** [comment]
This is just a foundation component. 

You can add your custom style or use https://ant.design/components/pagination/
