### ISSUE TITLE
TypeError: Cannot read property 'toString' of null in page size options

### ISSUE THREAD

**Issue by MathiasMinacapilli** [react-component/pagination#292]
Hi, I'm getting this error:
![image](https://user-images.githubusercontent.com/35637816/88571651-6162a700-d014-11ea-9254-1f6d0d154053.png)

Maybe, the code could check if the option is not null in the following piece of code:
![image](https://user-images.githubusercontent.com/35637816/88571786-8c4cfb00-d014-11ea-8ddc-edd7b7723519.png)
![image](https://user-images.githubusercontent.com/35637816/88572010-dafa9500-d014-11ea-94d2-36d555d3d9a1.png)

This code is located in `Options.jsx` file.

**Comment by 07akioni** [comment]
Could you give a reproduction link?

**Comment by MathiasMinacapilli** [comment]
It was a failure from our side. We were sending `null` in `pageSize` prop. The ticket can be closed. Thanks!
