### ISSUE TITLE
can not highlight current page,can not use next and previous button

### ISSUE THREAD

**Issue by justnull** [react-component/pagination#32]
can not highlight current page,and can not use next and previous button.these two button can not work.
I can use other Function.
![qq 20160701175116](https://cloud.githubusercontent.com/assets/724861/16518266/77ccbac0-3fb4-11e6-88e4-3298f61d5d42.png)

**Comment by afc163** [comment]
reproduce demo？

**Comment by justnull** [comment]
cause the type of variable pass to  the `current` is string.
