### ISSUE TITLE
Accessbility issues

### ISSUE THREAD

**Issue by yuzdeng** [react-component/pagination#345]
For now when you run `Siteimprove accessbility checker` tool in pagination component there are several issues popup.  The main issues are the label missing of page size dropdown and the jumper like the picture show.
![issue1](https://user-images.githubusercontent.com/19386255/132446476-6e5f7c38-b8db-4cb0-bbf9-5f6dab036059.jpeg)
![issue3](https://user-images.githubusercontent.com/19386255/132446481-3f37fe00-c176-4660-ab63-8b298826f252.jpeg)
![issue2](https://user-images.githubusercontent.com/19386255/132446493-3ecdc406-4adc-4aea-b4f7-7755ebcd6586.jpeg)

The version I test is 3.1.9. The way to fix it is adding the `arial-label` to the `Select` and  `input`. Can you add me to your contributor then I can create a pr for these issues? Thanks
![image](https://user-images.githubusercontent.com/19386255/132445861-255c676f-1b52-4904-9451-6514e484ebe1.png)

**Comment by yoyo837** [comment]
close by #346
