### ISSUE TITLE
Type error of pagination

### ISSUE THREAD

**Issue by jibenziliao** [react-component/pagination#349]
https://github.com/react-component/pagination/blob/ca84b62517e3447db1c4326dc3e9d7b599615034/rc-pagination.d.ts#L55
与antd中itemRender类型定义不一致，在Typescript tsc检测时会报错

https://github.com/ant-design/ant-design/blob/7d68eca271a4623b2474cdc6d435d6805aec8f35/components/pagination/Pagination.tsx#L25

相关issue https://github.com/ant-design/ant-design/pull/32393

**Comment by afc163** [comment]
https://github.com/react-component/pagination/pull/356
