### ISSUE TITLE
'rc-pagination-jump-next' button won't show.

### ISSUE THREAD

**Issue by kvoth3** [react-component/pagination#44]
Hi, great component. I'm having issue trying to show the 3 dotted button that jumps to pages in between range. Like this example here http://react-component.github.io/pagination/examples/jumper.html

I don't want the jumper where you type in page, i want button that skips pages.
It doesn't show for me unless I put a very large number for "total" property. But I want to show if number of pages exceed limited space.

this is what i get https://gyazo.com/6236a3892a5b2ce4899dfc461e39a654

I want it to show  like:

1 2 3 . . . 8 9

or something like that. Is it possible? I don't see parameters in documentation to make it show.

**Comment by paranoidjk** [comment]
just set `showLessItems={3}`, this api is on the bottom of the api list https://github.com/react-component/pagination#api.

maybe our document doesn't describe  very clear, welcome to give us a PR.
