### ISSUE TITLE
How to "Previous" arrow into text?

### ISSUE THREAD

**Issue by Youthink** [react-component/pagination#49]
use "上一页"  instead of "←"  ？

**Comment by yesmeck** [comment]
`locale` https://github.com/react-component/pagination#pagination

**Comment by Youthink** [comment]
@yesmeck http://react-component.github.io/pagination/examples/default.html
I mean the arrow in the sample.The arrow in the source is defined in css.

**Comment by paranoidjk** [comment]
@yesmeck right now it's been hardcode https://github.com/react-component/pagination/blob/master/src/Pagination.jsx#L370

**Comment by Youthink** [comment]
@paranoidjk @yesmeck 

I suddenly realized that I could use the method that covered the css style to achieve the effect I wanted.

```
.rc-pagination-prev a:after {
    content: "上一页";
    display: block;
    ...
}
```
