### ISSUE TITLE
Error while installing with yarn

### ISSUE THREAD

**Issue by vlkpa** [react-component/pagination#516]
yarn@3.1.1
`yarn add rc-pagination`

I am facing this error

`Error: While persisting /C:/<project>/.yarn/cache/rc-pagination-npm-3.3.0-1838abafd7-6b40cb2ab6.zip/node_modules/rc-pagination/ -> /C:/<project>/node_modules/rc-pagination ENOENT: no such file or directory, mkdir 'C:\<project>\node_modules\rc-pagination\dist\~demos\:id'`

**Comment by teamco** [comment]
under windows os you have no ability to creade folder / file started from colon :)
etc: 'C:\<project>\node_modules\rc-pagination\dist\~demos\**:id**'

**Comment by duan602728596** [comment]
The same problem. The current solution in window is 
```json
"resolutions": {
    "rc-pagination": "3.2.0"
}
```
if you use yarn.

**Comment by duypham90** [comment]
I still got error in window for now

Error: While persisting /E:/Projects/.yarn/cache/rc-pagination-npm-3.3.0-1838abafd7-6b40cb2ab6.zip/node_modules/rc-pagination/ -> /E:/Projects/node_modules/rc-pagination ENOENT: no such file or directory, mkdir 'E:\Projects\node_modules\rc-pagination\dist\~demos\:id'

**Comment by joesdu** [comment]
I still got error in window for now

Error: While persisting /G:/antdpro6-template/.yarn/cache/rc-pagination-npm-3.3.0-1838abafd7-6b40cb2ab6.zip/node_modules/rc-pagination/ -> /G:/antdpro6-template/node_modules/antd/node_modules/rc-pagination ENOENT: no such file or directory, mkdir 'G:\antdpro6-template\node_modules\antd\node_modules\rc-pagination\dist\~demos\:id'
