### ISSUE TITLE
Error while installing with yarn

### ISSUE THREAD

**Issue by joesdu** [react-component/pagination#521]
[#516 ]

Error: While persisting /G:/antdpro6-template/.yarn/cache/rc-pagination-npm-3.3.0-1838abafd7-6b40cb2ab6.zip/node_modules/rc-pagination/ -> /G:/antdpro6-template/node_modules/antd/node_modules/rc-pagination ENOENT: no such file or directory, mkdir 'G:\antdpro6-template\node_modules\antd\node_modules\rc-pagination\dist~demos:id'

**Comment by yoyo837** [comment]
安装3.3.1版本, 如果来自 antd, 删除node_modules和lock文件重新安装即可.

**Comment by joesdu** [comment]
> 安装3.3.1版本, 如果来自 antd, 删除node_modules和lock文件重新安装即可.

删除后还是,提问之前已经删掉重新安装了一次了.问题依旧

**Comment by yoyo837** [comment]
yarn why rc-pagination 看看

**Comment by joesdu** [comment]
> yarn why rc-pagination

➤ YN0001: │ Error: While persisting /G:/antdpro6-template/.yarn/cache/rc-pagination-npm-3.3.0-1838abafd7-6b40cb2ab6.zip/node_modules/rc-pagination/ -> /G:/antdpro6-template/node_modules/antd/node_modules/rc-pagination ENOENT: no such file or directory, mkdir 'G:\antdpro6-template\node_modules\antd\node_modules\rc-pagination\dist\~demos\:id'
➤ YN0000: └ Completed in 15s 458ms
➤ YN0000: Failed with errors in 16s 490ms
❯❯ antdpro6-template git:(main)  14:33 yarn why rc-pagination
├─ antd@npm:4.24.8                                                                                                                                                                                                                                                                                                  
│  └─ rc-pagination@npm:3.2.0 (via npm:~3.2.0)                                                                                                                                                                                                                                                                      
│                                                                                                                                                                                                                                                                                                                   
├─ antd@npm:5.3.2                                                                                                                                                                                                                                                                                                   
│  └─ rc-pagination@npm:3.3.0 (via npm:~3.3.0)                                                                                                                                                                                                                                                                      
│                                                                                                                                                                                                                                                                                                                   
├─ antd@npm:5.3.2 [1516b]                                                                                                                                                                                                                                                                                           
│  └─ rc-pagination@npm:3.3.0 [18b67] (via npm:~3.3.0 [18b67])                                                                                                                                                                                                                                                      
│                                                                                                                                                                                                                                                                                                                   
└─ antd@npm:4.24.8 [ff17e]
   └─ rc-pagination@npm:3.2.0 [07864] (via npm:~3.2.0 [07864])
❯❯ antdpro6-template git:(main) 14:33

**Comment by yoyo837** [comment]
<img width="379" alt="image" src="https://user-images.githubusercontent.com/6134547/227443739-9b17e261-ca85-4c44-9340-57c96116708a.png">


这不还是3.3.0么, 想办法更新到3.3.1

**Comment by yoyo837** [comment]
是不是有用私有npm镜像? 镜像里没同步到3.3.1?

**Comment by joesdu** [comment]
> 是不是有用私有npm镜像? 镜像里没同步到3.3.1?

没有设置私有镜像,我试试强制安装3.3.1试试.

**Comment by yoyo837** [comment]
antd 使用的 ` rc-pagination@~3.3.0`, 没有nod_modules和lock文件的情况下应该可以匹配到 3.3.1的.

**Comment by yoyo837** [comment]
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/6134547/227444492-d558d467-7786-406e-bbb6-88dd7e3c80d2.png">

**Comment by joesdu** [comment]
> antd 使用的 `rc-pagination@~3.3.0`, 没有nod_modules和lock文件的情况下应该可以匹配到 3.3.1的.

在项目中使用yarn add rc-pagination能检测到3.3.1但是还是无法安装,删掉node_modules重新安装还是不行

![image](https://user-images.githubusercontent.com/13188169/227444413-47b3518b-676d-4655-a3d4-3a7e2bc47ab2.png)

**Comment by yoyo837** [comment]
lock文件呢

**Comment by joesdu** [comment]
> lock文件呢

lock文件之前就已经删掉了,然后重新安装一直没成功,就没有生成lock文件,我试试把npm的cache清掉再重新安装试试
![image](https://user-images.githubusercontent.com/13188169/227444835-18aea66a-254b-489a-8e2b-6bd6af50821b.png)

**Comment by joesdu** [comment]
> lock文件删了没

刚没看到yarn.lock文件,我再试试.

**Comment by joesdu** [comment]
> lock文件删了没

搞定了,感谢大佬😘
