### ISSUE TITLE
#543 causes a typescript issue when building with the latest version of `rc-pagination`

### ISSUE THREAD

**Issue by heath-freenome** [react-component/pagination#547]
The change in #543 is causing a typescript issue when I am attempting to build with the latest version of `rc-pagination`
I'm seeing:
```
> tsc -b

node_modules/rc-pagination/lib/index.d.ts:2:1 - error TS1383: Only named exports may use 'export type'.

2 export type * from './interface';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

If you change this to `export * from `./interface` I believe things will do what you want and avoids this typescript error. This works fine because `interface.ts` is just a collection of types

**Comment by afc163** [comment]
Could you provide a reproduce codesandbox?

**Comment by heath-freenome** [comment]
Would a link to a failing repo branch work? I discovered this while attempting to upgrade the packages on the library I'm maintaining in https://github.com/rjsf-team/react-jsonschema-form

Here's the failing build: https://github.com/rjsf-team/react-jsonschema-form/pull/4006
