### ISSUE TITLE
It will always render an extra blank pagination item

### ISSUE THREAD

**Issue by ThyeeZz** [react-component/pagination#555]
It will recurrent when the page number is larger than 5, like the screenshot:
![image](https://github.com/react-component/pagination/assets/41352919/849eae07-213f-4f33-9eed-c98a151433fa)

**Comment by yoyo837** [comment]
Reproduction link please.

**Comment by ThyeeZz** [comment]
> recurrent

here, https://z2-dev.zilliz.cc/blog sorry it took some time to redeploy

**Comment by yoyo837** [comment]
Please provide a minimum editable reproduction link, such as [csb](https://codesandbox.io).

**Comment by ThyeeZz** [comment]
> Please provide a minimum editable reproduction link, such as [csb](https://codesandbox.io).

This blank item is the pageSizeOptions, but the default array is not working and I hide it by setting showSizeChanger to false
