### ISSUE TITLE
Add href in <a> tag to enable indexing by Google

### ISSUE THREAD

**Issue by thereviewindex** [react-component/pagination#61]
The anchor tag does not include the href attribute. 

Seems like, the <a> element isn't a link (:link) unless it has an [href] attribute. A side-effect of this is that an <a> element without [href] won't be indexed by Google.

Is it possible to have a callback for populating the href tag? (something that plays well with react-router)

Thanks!

(Ps: Thanks for the great component.)

**Comment by benjycui** [comment]
How about `Pagination[pagerContentRender]` for [this line of code](https://github.com/react-component/pagination/blob/f4b4720f41d0ac14300baa14fa4c633a034f3602/src/Pager.jsx#L19).

So you you can render it to be react-router's Link or other link element.

And we need to consider [prev and next](https://github.com/react-component/pagination/blob/f4b4720f41d0ac14300baa14fa4c633a034f3602/src/Pagination.jsx#L370), too.

**Comment by thereviewindex** [comment]
Clarifying - Are you suggesting eliminating the javascript [handleChange] and instead using [pagerContentRender] (which I presume will contain the relative path) ? Or supporting both as options?

**Comment by afc163** [comment]
itemRender ?
