### ISSUE TITLE
如何控制pagination跳转输入框内的数值？

### ISSUE THREAD

**Issue by xuchenchenBoy** [react-component/pagination#69]
断点调试下，选择Table的第index页，但是发现_current变化后，input内的value并没有改变。

    React.createElement('input', {
            type: 'text',
            value: this.state._current,
            onKeyDown: this._handleKeyDown,
            onKeyUp: this._handleKeyUp,
            onChange: this._handleKeyUp
    }),

**Comment by paranoidjk** [comment]
给出你的可重新代码示例或demo。
