### ISSUE TITLE
SPAN improper child of UL

### ISSUE THREAD

**Issue by kyleknighted** [react-component/pagination#71]
https://github.com/react-component/pagination/blob/master/src/Pagination.jsx#L374

It is improper markup to have a `span` as a child element of an `ul`.
This content should either precede or follow the actual pagination `ul`.
Also, with moving it outside of the UL, you _could_ add an option for `prepend || append`, or make it easy on yourself and just allow the user to provide their own custom styles (such as flexbox) to arrange the pager and the text however they want.

I will attempt to put together a PR for this if you'd like.

**Comment by paranoidjk** [comment]
sure, you can PR to replace totalText  `span` with ` li`.

but this is still not a `li` https://github.com/react-component/pagination/blob/master/src/Pagination.jsx#L390
