### ISSUE TITLE
Accessibility Updates

### ISSUE THREAD

**Issue by Logiraptor** [react-component/pagination#78]
We'd like to make the following accessibility updates to this component
- Allow customization of the numbered page button titles through the locale
- have screen readers interpret the `Next Page` and `Previous Page` as disabled when they are disabled.
Would these updates be ok?

**Comment by benjycui** [comment]
> Allow customization of the numbered page button titles through the locale

Maybe you can achieve this by https://github.com/react-component/pagination/issues/61#issuecomment-283839795

**Comment by benjycui** [comment]
> have screen readers interpret the Next Page and Previous Page as disabled when they are disabled.

So, could your PR to us?
