### ISSUE TITLE
dependency on `babel-runtime`?  

### ISSUE THREAD

**Issue by gmatroskin** [react-component/pagination#81]
Looks like starting `v1.8.9`, `rc-pagination` has a dependency on `babel-runtime`.  Is that intentional?   If so, I think `babel-runtime` needs to be added as a `peerDependency`.

**Comment by paranoidjk** [comment]
nope. please read babel doc

**Comment by gmatroskin** [comment]
Could you point me at the document you are referring to?  Our app does not include `babel-runtime`. `rc-pagination` worked fine without `babel-runtime` in `v1.8.7` and prior.  Starting `v1.8.9`, our bundling breaks with an unmet dependency.  

Your compiled modules (e.g. `lib/Pagination.js`) have dependencies on `babel-runtime`, e.g. `var _inherits2 = require('babel-runtime/helpers/inherits');`, since you started including `babel-runtime` in the build.  

If you are now requiring apps that rely on `rc-pagination` to also have a dependency on `babel-runtime`, you must include it into `peerDependencies` (see https://nodejs.org/en/blog/npm/peer-dependencies/).

**Comment by gmatroskin** [comment]
Documentation here (https://babeljs.io/docs/plugins/transform-runtime/#installation) seems to imply that you need to include `babel-runtime` in dependencies, which you are not doing:

![image](https://cloud.githubusercontent.com/assets/4924760/26234300/670e21fe-3c18-11e7-918e-9c673b6e3236.png)

**Comment by paranoidjk** [comment]
fixed, sorry, i lost babel-runtime in dependence by mistake.

**Comment by gmatroskin** [comment]
thanks for fixing so quickly!
