### ISSUE TITLE
分页goto输入框只限制输入数字的同时，不要禁用回退键啊。亲哥。

### ISSUE THREAD

**Issue by sunas** [react-component/pagination#90]
https://github.com/react-component/pagination/commit/812054ab2b567c49f528d3f34ab7c2ee573d95af

这个修改本意是为了限制小数的输入，但个人觉得，限制按键不是一个好方法，每次回车之后，对val的过滤应该更好。

**Comment by afc163** [comment]
My mistake.

**Comment by afc163** [comment]
Fixed in 1.9.7
