### ISSUE TITLE
onMouseClick

### ISSUE THREAD

**Issue by gaozhanglei** [react-component/pagination#97]
[http://react-component.github.io/pagination/examples/jumper.html](url)在提供的例子中，当出现两个领略页面的。。。时，点击向前跳转的”...“是，如果是跳转至1页就会报onMouseClick错误

**Comment by paranoidjk** [comment]
没复现。

你的文字描述我无法理解。

请给出可复现的 demo。

**Comment by gaozhanglei** [comment]
我知道什么原因引起的这个报错了，因为生成的分页是用的A标签，然后我在chrome上装了迅雷的扩展插件，所以会引起报错，sorry，不是组件的错。
